sudo: required
# Install docker
services:
  - docker

# Build test container
before_install:
  - docker build -t mdimatteo/udemy-docker-react -f Dockerfile.dev .

# Run test container
script:
  - docker run mdimatteo/udemy-docker-react npm run test -- --coverage

