sudo: required
# Install docker
services:
  - docker

# Build test container
before_install:
  - docker build -t mdimatteo/udemy-docker-react -f Dockerfile.dev .

# Run test container
script:
  - docker run mdimatteo/udemy-docker-react npm run test -- --coverage

# Deploy on AWS
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "udemy-docker-react"
  env: "UdemyDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-584052918819"
  bucket_path: "udemy-docker-react"
  on:
    branch: master
  access_key_id: $udemy-docker-react-aws-access-key
  secret_access_key:
    secure: $udemy-docker-react-aws-secret-key
